---
title: "Cleaning files"
author: "Sally Søgaard Andersen"
format: html
---

## Setup

```{r setup}
library(tidyverse)
source(here::here("R/functions.R"))
```

## Preparing HR data

```{r}
hr_data <- read_all("HR.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Preparing ibi data

```{r}
ibi_data <- read_all("IBI.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Preparing temp data

```{r}
temp_data <- read_all("TEMP.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Preparing bvp data

```{r}
bvp_data <- read_all("BVP.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Preparing eda data

```{r}
eda_data <- read_all("EDA.csv.gz") |>
  get_participant_id() |>
  summarise_by_datetime()
```

## Process survey data

```{r}
survey_tidy <- here::here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read() |>
  tidy_survey_dates()
```

```{r}
survey_long <- survey_tidy |>
  survey_to_long()
```

## Joining dataset
```{r}
nurses_stress <- survey_long |>
  full_join(survey_tidy) |>
  full_join(hr_data) |>
  full_join(eda_data) |>
  full_join(bvp_data) |>
  full_join(temp_data) |>
  full_join(ibi_data)

nurses_stress |>
  arrange(id, collection_datetime) |>
  view()
```

## writing to csv
```{r}
write_csv(nurses_stress, here::here("data/nurses-stress.csv"))
```
