---
title: "Learning R3 intermediate"
author: "Sally Søgaard Andersen"
format: html
---

## Setup

```{r setup}
library(tidyverse)
library(here)
library(fs)
source(here("R/functions.R")) # giver os adgang til vores R-script med funktioner
```

## Importing new data

```{r}
#| eval: false #gør at koden ikke kører (beholdes kun til noter ift. læring)

here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE, # printer ikke dens 'gæt' på kolonnetype
    name_repair = to_snake_case, # gør kolonne-navne til snake_case (nemmere at læse end PascalCase)
    n_max = 100 # bestemmer hvor mange rækker man læser ind fra filen (her 100), fx hvis man gerne vil lave noget prototype-kode hurtigt, så den ikke skal læse et kæmpe dataset ind
  )

# meget kodning hvis man skal skrive dette for hver fil (når der skal indlæses mange filer), så derfor har vi i stedet udarbejdet en funktion (read()), som findes under functions.R
```

## Using map to make hr dataset

```{r}
hr_files <- here("data-raw/nurses-stress/stress/") |>
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_data <- hr_files |>
  map(read) |> # ingen (), vi fortæller den at den skal bruge funktionen read, men vi skal ikke selv her aktivt bruge funktionen read()
  list_rbind(names_to = "file_path_id") # rowbind for at samle de mange tibbles til en. Argument names_to giver ID som er lig med filepath
```

## Exercise 18.5 Convert map to function and use on sleep

```{r}
## We made a new function called read_all, can be found under functions.R

hr_data <- read_all("HR.csv.gz")
ibi_data <- read_all("IBI.csv.gz")
bvp_data <- read_all("BVP.csv.gz")
```

## Exercise 19.2 Loading the survey data

```{r}
survey_data <- here("data-raw/nurses-stress/survey-results.csv.gz") |>
  read()
```

## Using regular expressions to extract text

```{r}
hr_data |>
  mutate(
    id = str_extract(
      file_path_id,
      pattern = "/stress/[:alnum:]{2}/" # extracts the complete match
    ) |>
      str_remove("/stress/") |> # fjern /stress/ fra navnet
      str_remove("/"), # fjern / fra navnet
    .before = file_path_id # sæt file_path_id kolonnen først
  ) |>
  select(-file_path_id)
```

## Exercise 19.7: convert get ID code into a function

```{r}
# we created a function called get_participant_id based on the above mentioned regex
# It can be found in functions.R
```

## Exercise 19.8: Simplify the regex with look arounds
```{r}
hr_data |>
  mutate(
    id = str_extract(
      file_path_id,
      pattern = "(?<=/stress/)[:alnum:]{2}(?=/)" # finder det eksakte match
    ),
    .before = file_path_id # sæt file_path_id kolonnen først
  ) |>
  select(-file_path_id)

# har her gjort regex mere præcis og kortere kode. Opdaterer get_participant_id funktionen med denne kode i functions.R
```
